base_url = "https://knownsh.cc"
compile_sass = true
build_search_index = true

title = "KnownSHcc"
theme = "anemone"

[markdown]
highlight_code = true

[extra]
list_pages = true
author = "KnownSH"

header_nav = [
  { url = "/", name_en = "home/" }
]
