base_url = "https://knownsh.cc"
compile_sass = false
build_search_index = true
default_language = "en"

title = "KnownSHcc"

[markdown]
render_emoji = true
highlight_code = true

[static.css]
custom = ["css/custom.css"]

[extra]
nav_links = [
  {url = "/", name = "home"},
  {url = "/about", name = "about"}
]