base_url = "https://www.knownsh.cc"
compile_sass = true
build_search_index = true

title = "KnownSH Mainpage"
theme = "after-dark"

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

after_dark_menu = [
    {url = "$BASE_URL", name = "Home"}
]

[markdown]
highlight_code = true

[extra]
author = "KnownSH"
